name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate action.yml
        run: |
          # install yamllint if needed
          pip install yamllint
          yamllint action.yml

      - name: Lint shell scripts
        run: |
          # install shellcheck if needed
          sudo apt-get update && sudo apt-get install -y shellcheck
          shellcheck entrypoint.sh

